# Generated by Django 3.2.9 on 2021-11-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_alter_transactionmodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='from_source',
            field=models.JSONField(default=list),
        ),
    ]
