# Generated by Django 3.2.9 on 2021-11-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_transactionmodel_from_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='amount_usd',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='timestamp',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='to_source',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='transaction_count',
            field=models.SmallIntegerField(default=0),
        ),
    ]
